### ISSUE TITLE
Make the Cloudant library programmatically extensible

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#103]
This library extends the Nano library by taking a Nano object and forcing the Cloudant-specific functions into the Nano object and into the "db" object that is created when "nano.db.use" is called.

This works but is a bit of a hack.

It would be nice if Nano (and by extension Cloudant) could be programmatically extensible e.g.

```
var spangle = function(opts, callback) {
     console.log("Spangle!");
     callback(null, null);
};
nano.extend("spangle", spangle);
nano.spangle({}, callback);
// Spangle!
```

Similarly for the "db" level extensions:

```
var spangle = function(opts, callback) {
     console.log("Spangle!");
     callback(null, null);
};

nano.extendDb("spangle", spangle);

var mydb = nano.db.use("mydb");
mydb.spangle({}, callback);
// Spangle!
```

If this were implemented in Nano, then this library could be refactored to simply "extend" Nano with its Cloudant-specific functions. Also it would allow _our library_ to be, in turn, extended by third parties.

Obviously the "extend" & "extendDb" function names are up for grabs.

**Comment by glynnbird** [comment]
Got top-level "extend" function working here: https://github.com/glynnbird/couchdb-nano/tree/extensible

Struggling with the db level version.

**Comment by jhs** [comment]
Hi, Glynn. A few thoughts.

Firstly, I really love how PouchDB implements plugins. https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-core/src/setup.js#L45-L54

Basically it jus puts all your functions in the object prototype. I just need to see about Nano, because Nano uses a lot more nested functions, rather than the prototype chain. But in any case, the PouchDB API is nice.

I think can be connected to #126, but I am now not totally sure. In your example, you are extending by adding a new method. However in some cases, we need to plug in to the existing machinery, like retrying on 429.

**Comment by ricellis** [comment]
Our new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/)(beta) follows a different model and doesn't depend on Nano. We're not going to do any more features here.
