### ISSUE TITLE
View search with a long query string fails

### ISSUE THREAD

**Issue by jlpadilla** [cloudant/nodejs-cloudant#108]
We are seeing a problem when we do a view search with a query parameter that is too long (about 3.5K chars).  I debugged the problem and I found that nano.js is issuing a GET request, which can be problematic with long queries.  To avoid this problem, the Cloudant documentation recommends using a POST request with the query parameters in the body.  Now, the problem is that I can't find any way to do this view search via a POST using cloudant.js (or nano.js).  I found that nano.js uses a POST when filtering by keys, but it still passes the query in the url instead of the body, so that can't be used to work around the problem.  The other alternative I found was to use nano's generic view() function, but this API isn't exposed.  I got it to work with a few hacks in nano.js, but can't find any possible way without modifying the libraries.

I feel this is a bug, unless I'm missing any other way to force the view search to use a POST with the query string in the body.

**Comment by glynnbird** [comment]
As you know, there is a limit to how long a query string can be. So long queries should be done by performing a "POST". As it stands, this library only ever does a GET request (the search function is implemented in Nano, by the way).

It think it's worth us sending search requests as POSTs to avoid the error you have found.

In the meantime, if you want a work-around, you can perform a custom operation using the `request` function to 'roll your own' custom request.

See https://github.com/apache/couchdb-nano#extending-nano

But your bug is noted and we'll get round to implementing a fix shortly.

**Comment by jlpadilla** [comment]
Thanks for the update!  I was able to get it to work with the mentioned workaround, but a permanent fix would be appreciated.

**Comment by jhs** [comment]
I will fix this in Nano. Thanks!

**Comment by glynnbird** [comment]
Can't fix this just yet. Waiting on a Cloudant ticket (77945).

**Comment by ricellis** [comment]
For a direct view query only the `keys` query parameter is accepted as part of a `POST` (and we do `POST` the keys). All the other query parameters are only accepted as part of the query string.
The `_search` for a design document can accept other parameters in the `POST`, Nano's view function will need an update to always `POST` if using the `type: 'search'`.

**Comment by ricellis** [comment]
All parameters are now permitted to be `POST`ed to views since CouchDB 3.0.0. Our new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/) supports sending all parameters this way via the `postView` function. If you still need a resolution for this problem we'd recommend migrating to that new SDK.
