### ISSUE TITLE
Array parameters already stringified get double-encoded.

### ISSUE THREAD

**Issue by xpqz** [cloudant/nodejs-cloudant#121]
If I pass a query object such as `{ include_docs: 'true', keys: '["test_doc_1453739724935"]' }` to say `db.list()` it gets double-encoded: `{ include_docs: 'true', keys: '"[\\"test_doc_1453739724935\\"]"' }`.

Not sure if this is a bug or expected behaviour. If it's the expected behaviour, perhaps it could be highlighted in the docs a bit? This is only an issue for parameters that are arrays (or objects) - maybe the endpoints that expect arrays can check this and do the right thing?

**Comment by glynnbird** [comment]
This needs to be fixed in Nano

**Comment by glynnbird** [comment]
key, keys, start_key & end_key are always JSON.encoded by Nano before dispatching to the server. We could 'intelligently' encode i.e. only encode things that aren't already encoded but that's way more difficult than it seems, not least because sometimes these parameters are just strings themselves. 

In short, if you supply a query object like this:

    { include_docs: 'true', keys: ["test_doc_1453739724935"] }

then you'll be ok.
