### ISSUE TITLE
Retriable HTTP requests

### ISSUE THREAD

**Issue by ricellis** [cloudant/nodejs-cloudant#126]
I'd like to open a discussion about potentially adding a way for nodejs-cloudant to retry HTTP requests for some conditions, e.g. for particular HTTP status codes. The request could be replayed at intervals with a doubling backoff and potentially use a value from a `Retry-After` header if the server provided one in a response.

I see that there are some modules such as https://www.npmjs.com/package/node-request-retry that appear to do this sort of thing. I guess incorporating anything like that might have to happen at the nano level. 
Another alternative might be adding an event listener for `'response'` events if it would be possible to have visibility to the original request to be able to replay it.

@glynnbird @jhs see also case 60008.

**Comment by ricellis** [comment]
Example configuration in [python-cloudant](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/client.py#L71) - starting at 250 ms backoff and doubling up to 10 times.

**Comment by glynnbird** [comment]
As per today's discussions we want to  ensure that this logic happens at the Cloudant level (not in Nano itself) because this status code will not be seen from CouchDB.

If Cloudant replies with a 429 status code, the library will pause for 0.5s and try the request again. The  pause will double each time, for a maximum of ten iterations. The user only has to make one function call; the exponential back-off is transparent to the user.

We do want to add some `stderr` logging to ensure that the user *knows* that we have retried on their behalf.

**Comment by ricellis** [comment]
Sorry @glynnbird I said 0.5 s on the phone, but we started at 0.25 s in java and python.

**Comment by glynnbird** [comment]
I've been sketching out solutions to this. I think it can be done but there’s a major gotcha as far as I can see.

If you use the `db.list(function(err, data) { } )` form, then we can hold off calling the callback until either a successful request comes, or our 10th attempt 429s. That's easy enough (I think).

The problem comes with the alternative method of calling functions which is the streaming api. e.g.

```
db.list().pipe(process.stdout);
```

The call to `db.list()` synchronously returns the `request` object that represents the HTTP request being made. In this scenario, the first request would be returned to the user, which would get a 429 response.

I can't see how a streaming user would be able to get the working request (if it isn't the first one). 

I'm going to sleep on it

**Comment by ricellis** [comment]
Is there any reason that the request returned synchronously has to be the first request? Maybe we can return a delegate/proxy that transparently retries and only delegates to the real request when it isn't a 429 or the retries are exhausted.

**Comment by ricellis** [comment]
@glynnbird any thoughts on my comment?

**Comment by jhs** [comment]
Hi, @ricellis. Right, I have done something similar with the Follow API. Technically it is embedded in this library too, but as a side feature.

I think the reason the request returned synchronously must be the first request because that is the only thing known at the time. In other words, by the time `db.list()` must return, the TCP SYN packet has not even left the machine. All `db.list()` has got is that delegate/proxy that you mention.

But the next problem is that we must adhere to this piping API. Typically that passes errors through to the user to deal with.

@glynnbird It looks like the only solution is not to return that request object back, but rather to return a stream. This stream can retry, timeout, etc. as needed like how my Follow library works. Assuming things go well, or even mostly well (i.e. a few retries but no big problems), then the user will just see the streaming data coming in (perhaps with a delay here and there if they are eagle-eyed).

@ricellis Does that work for you?

**Comment by ricellis** [comment]
@jhs thanks, sounds reasonable to me. Does that change from request to stream mean breaking the API?

**Comment by ricellis** [comment]
@jhs @glynnbird 
> If Cloudant replies with a 429 status code, the library will pause for 0.25s and try the request again. The pause will double each time, for a maximum of ten iterations. The user only has to make one function call; the exponential back-off is transparent to the user.

After a bit more discussion and feedback it is probably preferable to make this backoff optional and configurable, perhaps with an easy to add default of 3 retries starting at 0.25 s.

**Comment by jhs** [comment]
Glynn notes to (at least) log retries, so that people can determine what's going on if they feel high latency.

**Comment by ricellis** [comment]
@jhs here are the examples from the other libs:

Java:
The interceptor is at:
https://github.com/cloudant/java-cloudant/blob/master/cloudant-http/src/main/java/com/cloudant/http/interceptors/Replay429Interceptor.java
It gets added when the client is built via:
https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java#L441
e.g. https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java#L621

Python:
The adapter is here:
https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/adapters.py#L23
it is added when the client is created at:
https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/client.py#L47

**Comment by jhs** [comment]
Conclusion:

* Use Nano's `.request` option to override our own request implementation.
* If the user supplies retry:true, then we will support that, but we document that that may break streaming, because we might have to throw away the original request object and make a new one.

**Comment by ricellis** [comment]
Think this got covered with the retry plugin: https://github.com/cloudant/nodejs-cloudant#the-retry-plugin
