### ISSUE TITLE
Support several plugins at the same time

### ISSUE THREAD

**Issue by l2fprod** [cloudant/nodejs-cloudant#175]
The library supports *request* plugins (https://github.com/cloudant/nodejs-cloudant#request-plugins) but only one can be specified.

What if I want to enable the retry and promises?

**Comment by glynnbird** [comment]
Not an unreasonable request. The problem comes with streams. The retry plugin does support streams by returning Stream.PassThrough object but the promises library does not, as it returns a Promise. 

Ultimately, I'd like to make it so that the plugins become  series of options:

- retry: true (retry the request n times)
- session: true (exchange auth credentials for a cookie)
- promises: true (return a promise)
- stream: true (return a stream)

Effectively `promises` and `stream` couldn't both be true. 

I implemented the functionality separately as plugins to allow folks to test the new code without breaking the default behaviour which is to map each function call to one (and only one) API call.

**Comment by homerjam** [comment]
It's pretty straight forward to `promisifyAll` the things so why not just drop the promises plugin in favour of the more difficult features?
