### ISSUE TITLE
Retry plugin leaks "Typed Arrays" when used to download attachments

### ISSUE THREAD

**Issue by l2fprod** [cloudant/nodejs-cloudant#179]
In my app https://github.com/IBM-Bluemix/openwhisk-darkvisionapp I found that if I use the retry plugin and download an attachment from the database, the node.js process memory is increasing up to the point where it gives an out of memory. My node process is given 256MB (it runs inside an OpenWhisk action).

I tried to isolate the issue 

If I use `visionDb.attachment.get('123456', 'video.mp4').pipe(outputStream)`, I can see the memory increasing during the download. visionDb has the retry plugin enabled.

If I use request directly `request.get('http://cloudant/mydb/123456/video.mp4').pipe(outputStream)` everything runs smoothly. Same if I remove the `retry` plugin.

To reproduce the issue, put a 200MB attachment in a Cloudant document, then download the document with only 256MB allocated to node.js `node --max_old_space_size=256  downloadtest.js`

```
const fs = require('fs');
const output = fs.createWriteStream('test.mp4');

const Cloudant = require('cloudant');
const mydb = Cloudant({
  url: 'https://XXX:YYY@host',
  plugin: 'retry',
  retryAttempts: 10,
  retryTimeout: 500
}).db.use('medias');

mydb.attachment.get('yourid', 'video.mp4')
  .pipe(output)
  .on('finish', () => {
     console.log('write complete');
  })
  .on('error', (err) => {
    console.log('error while writing', err);
  });
```

The reference to "Typed Arrays" in the title comes to the observation I made when running the chrome debugger with `node --max_old_space_size=256 --inspect --debug-brk``` and recording heap profile.

**Comment by glynnbird** [comment]
The "default" plugin makes a single API call to Cloudant for every request. In this way, it's easy for the library to return the Stream to you synchronously. You can then "pipe" the stream to a file or somewhere else without issue.

The "retry" plugin can't return you the stream that relates to the API call it makes because it might not be the first attempt. The first, second, third API call might get a 429, the fourth one may succeed but we don't know that until we try.

To get around this, the "retry" plugin returns you a [Stream.PassThrough](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) object synchronously and pipes the result of a successful call to *that* stream, which in turn is passed on to you. This trick is obviously incurring some additional memory consumption in the Node app. Node *should* garbage collect the data to keep things running, and I would expect the output stream (the file) to be able to cope with the data arriving from the input stream (Cloudant).

**Comment by smithsz** [comment]
Fixed in commit https://github.com/cloudant/nodejs-cloudant/pull/198/commits/a344ff2cec431df345d1ad0c496219f0598c9039.

Previously the retry plugin would pass a callback to `requests` even if the client didn't specify one. As a result the entire response was being stored in memory until the noop callback was executed. This change uses the `response` event to check for a 429 and possibly retry the request.
