### ISSUE TITLE
getting 413 on couchimport from node.js cmd prompt

### ISSUE THREAD

**Issue by rashmi-ved** [cloudant/nodejs-cloudant#222]
Please include the following information in your ticket.

- Cloudant (nodejs-cloudant) version(s) that are affected by this issue.: Bluemix->cloudantLite
- Node version:  6.11.4 (x64)
- A small code sample that demonstrates the issue."

hi I am still getting 413 and my file size is 883KB
using node.js command prompt from my windows 7. executed below cmd
type <.csv filename> | couchimport

getting below response:
headers:
{ 'cache-control': 'must-revalidate',
'content-type': 'application/json',
date: 'Fri, 06 Oct 2017 09:08:56 GMT',
'x-couch-request-id': '29d20bd73e',
'x-frame-options': 'ALLOW-FROM https://046d20cf-f1bc-4888-bfce-235b22c40752
-bluemix.cloudant.com',
'strict-transport-security': 'max-age=31536000',
'x-content-type-options': 'nosniff',
'x-cloudant-request-class': 'write',
'x-cloudant-backend': 'bm-cc-us-south-01',
via: '1.1 lb1.bm-cc-us-south-01 (Glum/1.40.0)',
statusCode: 413,
uri: 'https://XXXXXX:XXXXXX@046d20cf-f1bc-4888-bfce-235b22c40752-bluemix.cl
oudant.com/arrayantdb/_bulk_docs' },
errid: 'non_200',
description: 'couch returned 413' } +1s
couchimport writecomplete { total: 0, totalfailed: 0 } +3s
couchimport Import complete +0ms

**Comment by glynnbird** [comment]
This is probably the wrong place to raise the issue but I'll answer it here anyway.

You are getting a 413 error code because a request you made to Cloudant exceed it's maximum permitted size of 1MB. Try reducing the number using the `--buffer` command-line option, passing in a smaller number e.g. `--buffer 100`. This should ask `couchimport` to write fewer documents at a time and may fix your problem.

**Comment by ricellis** [comment]
It's worth noting that even if the `.csv` file is 883 KB, the JSON will be larger because the csv file likely contains the keys only once in the first row, but those keys will be duplicated with the values in each JSON document.

Like I said in the other issue the correct repository for this is [couchimport](https://github.com/glynnbird/couchimport/issues), but as Glynn says, hopefully you can tune the buffer size to keep the requests under 1 MB and avoid the 413.

**Comment by rashmi-ved** [comment]
thank you very much for prompt response. reduced the file size and it worked
is there a way to define documentName which gets created to keep track which csv data it is. can see id, key and value for each doc

**Comment by rashmi-ved** [comment]
posted here since it is related to my prev request

**Comment by glynnbird** [comment]
not really. But you can use transform functions to do arbitrary things. You provide a function that is called once for each document before it's written to the database. You could add your own custom fields that way.

**Comment by rashmi-ved** [comment]
ok 
any example of transform.js tried earlier searching for but did not find any

**Comment by rashmi-ved** [comment]
not able to find example directory that you have mentioned

**Comment by glynnbird** [comment]
try here: https://github.com/glynnbird/couchimport/tree/master/examples

**Comment by rashmi-ved** [comment]
how to pass _id as combination of a literal and raw number 
"20171006-" + rownum

to get _id like below:
20171006-1
20171006-2
20171006-3 and so on

not able to get clue from anywhere

**Comment by rashmi-ved** [comment]
what is the placeholder for current raw of a .csv file being processed. 
or can a static var be declared

**Comment by rashmi-ved** [comment]
how to use raw.fields(0)
need help
