### ISSUE TITLE
When the next version will be released ?

### ISSUE THREAD

**Issue by gusdaud** [cloudant/nodejs-cloudant#304]
Hey, when the next version will be released ?

I really need to use the promises and retry plugins and the current version doesn't seem to support multiple plugins.

**Comment by ricellis** [comment]
As per the [release notes](https://github.com/cloudant/nodejs-cloudant/releases) multiple plugins has been available since 2.0.1. The current release is version 2.1.0. Note that the 2.x releases are in the `@cloudant` NPM scope so the package is [`@cloudant/cloudant`](https://www.npmjs.com/package/@cloudant/cloudant) instead of the old `cloudant`.

**Comment by gusdaud** [comment]
I didn't know (about the package), I'm glad I've asked.Thanks!!

**Comment by ricellis** [comment]
Np, sorry if it wasn't clear we tried to update all the docs and NPM should show a message like:
`npm WARN deprecated cloudant@1.10.0: This package is now scoped. The new name is @cloudant/cloudant`

**Comment by gusdaud** [comment]
No worries, thanks again
