### ISSUE TITLE
maxConnections is set to 6 instead of the Node default of Infinity

### ISSUE THREAD

**Issue by tdc9998** [cloudant/nodejs-cloudant#315]
On line 171 of `lib/client.js` maxSockets are set to 6. Originally, Node specified a limit on the number of connections, but the value is now `Infinity` by default. (I believe this was changed in Node 0.4.)

I realize it's possible to create a custom client, but wouldn't it be more appropriate to keep maxConnections consistent between Node and the Cloudant client API?

Here's a link to the relevant Node documentation:
https://nodejs.org/api/http.html#http_agent_maxsockets

I've discussed this with @kocolosk, so please feel free to talk with him about any concerns.

**Comment by emlaver** [comment]
@tdc9998 The max connections size is set to 6 across all of our client libraries.  You can configure `maxSockets` during the initialization of the client with a custom agent:
e.g.
```
var protocol = require('https')
var myagent = new protocol.Agent({
  keepAlive: true,
  keepAliveMsecs: 30000,
  maxSockets: 6
});
var cloudant = require('@cloudant/cloudant')({ account:"me", password:"secret", requestDefaults: { agent: myagent } });
```

**Comment by kocolosk** [comment]
@emlaver thanks. Is this well-known? I couldn't find it documented anywhere. It seems to me that if we're overriding the default for Node HTTP clients we should write that down somewhere.

**Comment by emlaver** [comment]
@kocolosk I'm not sure if it's well-known but we can open an issue and add this to the documentation.  We do have docs for configuring the pool size: https://github.com/cloudant/nodejs-cloudant/blob/master/README.md#pool-size-and-open-sockets.

**Comment by tdc9998** [comment]
I guess I'd ask this: Is there a good reason why `maxSockets` is set to six across all libraries? (i.e. are there problems with using the default value?) If not, then it's counter-intuitive to put an artificial limit in place. Couldn't you simply avoid setting `maxSockets`, and allow the underlying platform to use their default values? (If you're going for consistency, that's probably the best bet.)

**Comment by tomblench** [comment]
@tdc9998 this default is line with other libraries, for example [macOS/iOS](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407597-httpmaximumconnectionsperhost?language=objc) 

If you really do want `Infinity` connections, you'll end up running out of underlying OS sockets, file descriptors, etc. For most applications we tend to find that any benefits from multiple connections tend to diminish after around 6 or even 4. 

Closing since we provide a sensible default and we have provided clear documentation showing how the user can change it.
