### ISSUE TITLE
wrong documentation of set_security

### ISSUE THREAD

**Issue by kayoub5** [cloudant/nodejs-cloudant#79]
according to documentations `set_security` accepts a `security` object.
https://github.com/cloudant/nodejs-cloudant#generate-an-api-key
but it is implemented in a way, it only accepts permissions (`security.cloudant`)
https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L92

**Comment by glynnbird** [comment]
There was a problem with the documentation of `set_security` which was fixed with this commit: https://github.com/cloudant/nodejs-cloudant/commit/ab7add7d403c32d4e76b5206d47d56ef943c6162 with a further error fixed here https://github.com/cloudant/nodejs-cloudant/commit/cfa78725d3c414ef9a59d6f03a8986e97c738ba2.

Apologies for the confusion. These changes should be released in 10 days. Please see the documentation at https://github.com/cloudant/nodejs-cloudant for the the latest documentation.
