### ISSUE TITLE
Change "destroy" to "delete"

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#9]
Why call it destroy?

**Comment by jhs** [comment]
/cc @glynnbird @mikerhodes 

Have you got any opinion about this? I think we call it "destroy" from the Nano heritage, however in my opinion "delete" is more user-friendly since they will have seen that from other documentation (and that is the HTTP method in the REST API).

My feeling is set it to `delete()` and support `destroy()` with a deprecation warning.

I am setting as a 2.0 milestone since it would be an API change.

**Comment by glynnbird** [comment]
I say create an alias function if you need to but I am very keen on nodejs-cloudant being a drop in replacement for Nano. There will be users who are using Nano + CouchDB, they then decided they wanted a hosted solution and move to Cloudant. They should then be able to use nodejs-cloudant + Cloudant and not modify any code. 

Nano uses different verbs to the RESTful API (insert instead of post/put, destroy instead of delete). I think it would cause more grief to users to change it.

**Comment by jhs** [comment]
Yes, I agree that nodejs-cloudant should be a drop-in replacement for Nano. That is an excellent point.

Perhaps the correct solution is to persuade the community that Nano's verbs could use a change, and then let those changes trickle down to use. (Major version changes, of course.)

**Comment by ricellis** [comment]
Closing as stale, this can be handled upstream in nano.
